// RTP simulation + calibration.
//   node tools/sim.mjs                 -> calibrate every game, write src/rtp.js
//   node tools/sim.mjs gold bass       -> only these games
//   node tools/sim.mjs --check [ids]   -> just report with the current src/rtp.js
//   --spins=N  (default 400000 base spins)
import { writeFileSync, readFileSync } from "node:fs";
import { GAMES, RTP_TARGET } from "../src/games.js";
import { spin, newSession } from "../src/engine.js";

const args = process.argv.slice(2);
const check = args.includes("--check");
const N = Number((args.find(a => a.startsWith("--spins=")) || "").slice(8)) || 400000;
const ids = args.filter(a => !a.startsWith("--"));
const games = GAMES.filter(g => !ids.length || ids.includes(g.id));

function mulberry32(a) {
  return () => {
    a |= 0; a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

function run(game, n, seed) {
  const rng = mulberry32(seed);
  const ses = newSession();
  let cost = 0, win = 0, hits = 0, fsTrig = 0, max = 0, sq = 0, spins = 0;
  for (let i = 0; i < n; i++) {
    let round = 0;
    cost += 1;
    let r = spin(game, 1, ses, rng);
    spins++;
    if (r.total > 0) hits++;
    if (r.fsAwarded) fsTrig++;
    round += r.total;
    while (ses.fsLeft > 0) { r = spin(game, 1, ses, rng); spins++; round += r.total; }
    win += round; sq += round * round;
    if (round > max) max = round;
  }
  const mean = win / n;
  return { rtp: win / cost, hit: hits / n, fs: fsTrig ? n / fsTrig : Infinity, max, sd: Math.sqrt(sq / n - mean * mean), spins };
}

const scales = {};
try {
  const m = readFileSync(new URL("../src/rtp.js", import.meta.url), "utf8").match(/SCALE = (\{[\s\S]*?\});/);
  if (m) Object.assign(scales, JSON.parse(m[1]));
} catch { /* first run */ }

const fmt = (x, d = 2) => x.toFixed(d);
console.log("game      mode     scale   RTP%   hit%   FS 1/x   maxWin  volatility(sd)");
for (const g of games) {
  if (!check) {
    g.scale = 1;
    const a = run(g, N, 1);
    g.scale = RTP_TARGET / a.rtp;
    const b = run(g, N, 2);
    g.scale *= RTP_TARGET / b.rtp;           // second pass absorbs the max-win cap and noise
    scales[g.id] = Number(g.scale.toPrecision(5));
  }
  const v = run(g, N, check ? 7 : 3);
  console.log(
    g.id.padEnd(9), g.mode.padEnd(8), fmt(g.scale, 3).padStart(6),
    fmt(v.rtp * 100).padStart(6), fmt(v.hit * 100, 1).padStart(6),
    (v.fs === Infinity ? "-" : fmt(v.fs, 0)).padStart(7), fmt(v.max, 0).padStart(8), fmt(v.sd, 1).padStart(8)
  );
}
if (!check) {
  const all = {};
  for (const g of GAMES) all[g.id] = scales[g.id];
  writeFileSync(new URL("../src/rtp.js", import.meta.url),
    "// Generated by tools/sim.mjs — per-game pay scale that lands RTP on the target.\n" +
    "export const SCALE = " + JSON.stringify(all, null, 2) + ";\n");
  console.log("wrote src/rtp.js");
}
