// Generated by tools/sim.mjs — per-game pay scale that lands RTP on the target.
export const SCALE = {
  "gold": 17.474,
  "sweet": 9.5706,
  "olympus": 30.393,
  "bass": 17.428,
  "piggy": 19.503,
  "dog": 4.6651,
  "star": 2.8988,
  "nova": 25.198,
  "dragon": 8.7464,
  "bounty": 6.1057,
  "frenzy": 16.548,
  "royal": 2.1385,
  "alien": 9.8564
};
